version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped

  chat-server:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Server=db;Database=ProjectChat;User Id=sa;Password=P@ssw0rd123;TrustServerCertificate=True
    restart: unless-stopped

volumes:
  sqldata: